import { StyleSheet } from 'react-native'
import { theme } from './theme'

export const commonStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  decorTop: {
    position: 'absolute',
    top: -120,
    right: -80,
    width: 290,
    height: 290,
    borderRadius: 145,
    backgroundColor: theme.colors.primarySoft,
    opacity: 0.85,
  },
  decorBottom: {
    position: 'absolute',
    bottom: -120,
    left: -90,
    width: 270,
    height: 270,
    borderRadius: 135,
    backgroundColor: theme.colors.accentSoft,
    opacity: 0.78,
  },
  pageWrap: {
    flex: 1,
  },
  content: {
    padding: theme.spacing.md,
    paddingBottom: 110,
  },
  card: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: theme.spacing.md + 2,
    ...theme.shadow,
  },
  sectionTitle: {
    fontSize: 21,
    fontWeight: '800',
    letterSpacing: 0.3,
    color: theme.colors.text,
    marginBottom: theme.spacing.sm,
  },
  bodyText: {
    fontSize: 15,
    color: theme.colors.text,
    lineHeight: 24,
  },
  input: {
    backgroundColor: theme.colors.surfaceSoft,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.sm,
    paddingHorizontal: 14,
    paddingVertical: 13,
    color: theme.colors.text,
  },
  stepLikeInput: {
    minHeight: 52,
    textAlignVertical: 'top',
  },
  primaryButton: {
    backgroundColor: theme.colors.primary,
    borderRadius: theme.radius.pill,
    minHeight: 48,
    paddingHorizontal: 20,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 7,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.pill,
    minHeight: 48,
    paddingHorizontal: 20,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.surfaceSoft,
  },
  secondaryButtonText: {
    color: theme.colors.text,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  bottomBar: {
    height: 98,
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
    backgroundColor: theme.colors.surface,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
    shadowColor: '#5D3B21',
    shadowOpacity: 0.1,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: -3 },
    elevation: 6,
  },
  bottomBorder: {
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    paddingBottom: 12,
    marginBottom: 6,
  },
})
